apiVersion: v1
kind: Service
metadata: 
  name: master
spec: 
  clusterIP: None
  ports: 
    - port: 11311
      protocol: TCP
      targetPort: 11311
  selector: 
    name: master
  externalIPs:
    - 172.17.8.101
